name: IELTS Writing Task 1 - AI vs Self Assessment
about: 用於紀錄每篇 Task 1 練習的自評、AI 評分與差異判斷
title: "[Task 1] {{title}}"
labels: ["IELTS", "Task 1", "AI Comparison"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 1️⃣ 基本資訊
        - 題目名稱/編號: 
        - 寫作日期: 
        - 題型: （Line / Bar / Pie / Table / Map / Process / Mixed）
        - 時間限制: 20 分鐘

  - type: textarea
    id: self_assessment
    attributes:
      label: "2️⃣ 自我評估分數 (Self Assessment)"
      description: "對照 IELTS 四大核心維度，填寫自評分數 0~9"
      placeholder: |
        Task Response (TR): 
        Coherence & Cohesion (CC): 
        Lexical Resource (LR): 
        Grammatical Range & Accuracy (GRA): 
        其他觀察/備註: 

  - type: textarea
    id: ai_assessment
    attributes:
      label: "3️⃣ AI 評分 (AI Scoring)"
      description: "將 AI 提供的分數與評語填入"
      placeholder: |
        Task Response (TR): 
        Coherence & Cohesion (CC): 
        Lexical Resource (LR): 
        Grammatical Range & Accuracy (GRA): 
        AI 評語: 

  - type: checkboxes
    id: difference_analysis
    attributes:
      label: "4️⃣ 差異判斷 (Difference Analysis)"
      description: "勾選符合本篇的類型，並補充原因與判斷"
      options:
        - label: "自評高 / AI 低 → 自我盲點"
        - label: "自評低 / AI 高 → 認知保守"
        - label: "自評 ≈ AI → 共識問題"
        - label: "分數接近但理由不同 → 認知偏差"
  
  - type: textarea
    id: reflection_action
    attributes:
      label: "5️⃣ 背脊反思與行動 (Reflection & Action)"
      description: "針對每個差異類型，列出具體修正行動（重寫段落 / 收錄最佳範例 / micro drills / 驗證 AI 理由）"
      placeholder: |
        - 自我盲點修正: 
        - 認知保守收錄: 
        - 共識問題訓練: 
        - 理由偏差驗證: 

  - type: textarea
    id: additional_notes
    attributes:
      label: "6️⃣ 其他備註 (Optional Notes)"
      description: "可記錄寫作過程中的心得、詞彙卡片或額外觀察"
      placeholder: ""
