name: Download Issue Images on Close

on:
  issues:
    types: [closed]

jobs:
  download-images:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get issue body
        id: get_issue_body
        run: echo "body<<EOF" >> $GITHUB_ENV && echo "${{ github.event.issue.body }}" >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV

      - name: Download images
        env:
          ISSUE_BODY: ${{ env.body }}
        run: |
          mkdir -p images
          echo "$ISSUE_BODY" | grep -o 'https://github.com/[^ ]*assets/[^ ]*' | while read url; do
            filename=$(basename "$url")
            curl -L -o "images/$filename" "$url"
            echo "Downloaded: $filename"
          done