name: Validate Task File & Suggest Candidates

on:
  issues:
    types: [opened]

jobs:
  validate_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Parse file name from issue
        id: parse
        run: |
          echo "Parsing file name from issue body..."
          # 原始腳本的 jq 查詢失敗，因為它尋找的是 'task_file:'
          # 新的腳本使用 grep -oP 搭配 lookbehind，精準地從 '文章檔案連結' 後方提取檔案名稱。
          FILE_NAME=$(echo "${{ github.event.issue.body }}" | grep -oP '文章檔案連結\n\n\K.*' | head -n 1)
          
          # 檢查是否成功提取檔案名稱
          if [ -z "$FILE_NAME" ]; then
            echo "Error: Could not find '文章檔案連結' in issue body."
            exit 1
          fi

          echo "file_name=$FILE_NAME" >> $GITHUB_ENV
          echo "Extracted file name: $FILE_NAME"

      - name: List all txt files
        id: listfiles
        run: |
          FILES=$(find . -maxdepth 1 -name "*.txt" -printf "%f\n")
          echo "all_files=$FILES" >> $GITHUB_ENV
          echo "Available files: $FILES"

      - name: Check if file exists and suggest candidates
        run: |
          FOUND=false
          for f in ${{ env.all_files }}; do
            if [ "$f" = "${{ env.file_name }}" ]; then
              FOUND=true
              break
            fi
          done

          if [ "$FOUND" = true ]; then
            echo "File exists."
          else
            echo "File not found. Suggesting candidates..."
            # 確保使用正確的環境變數 ${{ env.file_name }} 和 ${{ env.all_files }}
            gh issue comment ${{ github.event.issue.number }} --body "⚠️ 檔案 `${{ env.file_name }}` 不存在！可選檔案如下:\n${{ env.all_files }}"
            exit 1
          fi

      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: file:${{ env.file_name }}

      - name: Add link comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ 檔案已驗證存在
            檔案連結: [${{ env.file_name }}](https://github.com/${{ github.repository }}/blob/master/${{ env.file_name }})
